on:
  push:
    branches:
      -main
jobs:
  test:
    runs: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: test
        run: |
          echo "good morning"
          echo "test"